[package]
name = "ksplit"
version = "0.1.0"
authors = ["jose <jose@autonomic.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4"
anyhow = "1.0"
